/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perfilusuario;

/**
 *
 * @author Carlos
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PerfilUserPanel = new javax.swing.JPanel();
        ToolsPanel = new javax.swing.JPanel();
        OpenToolPanel = new javax.swing.JPanel();
        OpenToolButton = new javax.swing.JButton();
        PerfilButton1 = new javax.swing.JButton();
        BusquedaButton = new javax.swing.JButton();
        CatalogoButton = new javax.swing.JButton();
        PerfilButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PerfilUserPanel.setBackground(new java.awt.Color(255, 255, 255));

        ToolsPanel.setBackground(new java.awt.Color(238, 238, 238));

        OpenToolPanel.setBackground(new java.awt.Color(255, 0, 0));

        OpenToolButton.setBackground(new java.awt.Color(204, 0, 0));
        OpenToolButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RayasTools.png"))); // NOI18N

        javax.swing.GroupLayout OpenToolPanelLayout = new javax.swing.GroupLayout(OpenToolPanel);
        OpenToolPanel.setLayout(OpenToolPanelLayout);
        OpenToolPanelLayout.setHorizontalGroup(
            OpenToolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpenToolPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(OpenToolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        OpenToolPanelLayout.setVerticalGroup(
            OpenToolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpenToolButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PerfilButton1.setBackground(new java.awt.Color(238, 238, 238));
        PerfilButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PerfilButton1.setText("Chats");
        PerfilButton1.setBorderPainted(false);

        BusquedaButton.setBackground(new java.awt.Color(238, 238, 238));
        BusquedaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BusquedaButton.setText("Busqueda");
        BusquedaButton.setBorderPainted(false);

        CatalogoButton.setBackground(new java.awt.Color(238, 238, 238));
        CatalogoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CatalogoButton.setText("Mi catálogo");
        CatalogoButton.setBorderPainted(false);

        PerfilButton.setBackground(new java.awt.Color(204, 204, 204));
        PerfilButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PerfilButton.setText("Perfil");

        javax.swing.GroupLayout ToolsPanelLayout = new javax.swing.GroupLayout(ToolsPanel);
        ToolsPanel.setLayout(ToolsPanelLayout);
        ToolsPanelLayout.setHorizontalGroup(
            ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolsPanelLayout.createSequentialGroup()
                .addGroup(ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PerfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OpenToolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CatalogoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(PerfilButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BusquedaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ToolsPanelLayout.setVerticalGroup(
            ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolsPanelLayout.createSequentialGroup()
                .addComponent(OpenToolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(PerfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CatalogoButton)
                .addGap(18, 18, 18)
                .addComponent(PerfilButton1)
                .addGap(18, 18, 18)
                .addComponent(BusquedaButton)
                .addGap(0, 222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PerfilUserPanelLayout = new javax.swing.GroupLayout(PerfilUserPanel);
        PerfilUserPanel.setLayout(PerfilUserPanelLayout);
        PerfilUserPanelLayout.setHorizontalGroup(
            PerfilUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilUserPanelLayout.createSequentialGroup()
                .addComponent(ToolsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
        );
        PerfilUserPanelLayout.setVerticalGroup(
            PerfilUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PerfilUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PerfilUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusquedaButton;
    private javax.swing.JButton CatalogoButton;
    private javax.swing.JButton OpenToolButton;
    private javax.swing.JPanel OpenToolPanel;
    private javax.swing.JButton PerfilButton;
    private javax.swing.JButton PerfilButton1;
    private javax.swing.JPanel PerfilUserPanel;
    private javax.swing.JPanel ToolsPanel;
    // End of variables declaration//GEN-END:variables
}
