/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perfildeusuario;
/**
 *
 * @author Carlos
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_PerfilUsuario = new javax.swing.JPanel();
        ScrollPane_Descripción = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Button_Contactar = new javax.swing.JButton();
        Button_Ajustes = new javax.swing.JButton();
        Button_Catalogo = new javax.swing.JButton();
        Label_Username = new javax.swing.JLabel();
        Label_ImagenPerfil = new javax.swing.JLabel();
        Panel_Estadisticas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Descripción");
        ScrollPane_Descripción.setViewportView(jTextArea1);

        Button_Contactar.setBackground(new java.awt.Color(204, 0, 0));
        Button_Contactar.setForeground(new java.awt.Color(0, 204, 255));
        Button_Contactar.setText("Contactar");

        Button_Ajustes.setBackground(new java.awt.Color(204, 0, 0));
        Button_Ajustes.setForeground(new java.awt.Color(0, 204, 255));
        Button_Ajustes.setText("Ajustes");

        Button_Catalogo.setBackground(new java.awt.Color(204, 0, 0));
        Button_Catalogo.setForeground(new java.awt.Color(0, 204, 255));
        Button_Catalogo.setText("Catálogo");

        Label_Username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label_Username.setText("Username");

        Label_ImagenPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserPerfil.png"))); // NOI18N

        Panel_Estadisticas.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout Panel_EstadisticasLayout = new javax.swing.GroupLayout(Panel_Estadisticas);
        Panel_Estadisticas.setLayout(Panel_EstadisticasLayout);
        Panel_EstadisticasLayout.setHorizontalGroup(
            Panel_EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel_EstadisticasLayout.setVerticalGroup(
            Panel_EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_PerfilUsuarioLayout = new javax.swing.GroupLayout(Panel_PerfilUsuario);
        Panel_PerfilUsuario.setLayout(Panel_PerfilUsuarioLayout);
        Panel_PerfilUsuarioLayout.setHorizontalGroup(
            Panel_PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PerfilUsuarioLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(Label_Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Catalogo)
                .addGap(51, 51, 51)
                .addComponent(Button_Contactar)
                .addGap(46, 46, 46)
                .addComponent(Button_Ajustes)
                .addGap(71, 71, 71))
            .addGroup(Panel_PerfilUsuarioLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(Label_ImagenPerfil)
                .addGap(54, 54, 54)
                .addComponent(ScrollPane_Descripción, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(Panel_PerfilUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Estadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_PerfilUsuarioLayout.setVerticalGroup(
            Panel_PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PerfilUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Panel_PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane_Descripción, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_ImagenPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_Catalogo)
                        .addComponent(Button_Contactar)
                        .addComponent(Button_Ajustes))
                    .addComponent(Label_Username))
                .addGap(18, 18, 18)
                .addComponent(Panel_Estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_PerfilUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_PerfilUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Ajustes;
    private javax.swing.JButton Button_Catalogo;
    private javax.swing.JButton Button_Contactar;
    private javax.swing.JLabel Label_ImagenPerfil;
    private javax.swing.JLabel Label_Username;
    private javax.swing.JPanel Panel_Estadisticas;
    private javax.swing.JPanel Panel_PerfilUsuario;
    private javax.swing.JScrollPane ScrollPane_Descripción;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
